### ISSUE TITLE
Shadow of Time Vortex remains after remat

### ISSUE THREAD

**Issue by benrob0329** [MattJeanes/TARDIS#177]
![20160905112414_1](https://cloud.githubusercontent.com/assets/19180682/18258251/3e75f820-73a0-11e6-9057-ecd8c01ba9c7.jpg)

It turns with the TARDIS as well, so I'm assuming that its turned invisible when rematting, and teleported to the TARDIS when dematting?

A better alternative would be to despawn on remat (or despawning of TARDIS) as that would remove the shadow.

**Comment by MattJeanes** [comment]
Are you able to consistently reproduce this issue even after restarting your game and on different maps? Make sure all your addons are up to date too and no old versions are left around.

**Comment by benrob0329** [comment]
All addons that are relevant are from the workshop.

That screenshot was from earlier today, and it still can be consistently reproduced on several different maps.

**Comment by MattJeanes** [comment]
This should be fixed as of https://github.com/MattJeanes/TARDIS/commit/d75a854a1f7853db528e889518eaf9a94afe4714 - can you confirm before I close this?

**Comment by benrob0329** [comment]
As of latest workshop, no.

As of latest Git, I can't seem to get Gmod to run the mod, it just doesn't show up in the spawn menu!

**Comment by MattJeanes** [comment]
Make sure you've got Doors and world-portals teleport branch installed if
you're going all git

**Comment by benrob0329** [comment]
I'm probably doing really obviously wrong, but it just doesn't seem to work for me!

I have TARDIS, Doors, and world-portals (and I ran '''git branch teleport''') all cloned into my addons folder, and the workshop versions uninstalled (and I checked for the GMAs), but it still doesn't show up!

I even removed a crap ton of addons, just to make sure that I didn't have too many installed.

The only workshop addon that I have enabled is the Vortex pack.

**Comment by MattJeanes** [comment]
You need to do `git checkout teleport-beta`, just clone it using GitHub desktop or download the zip or something.

**Comment by benrob0329** [comment]
It apears to load everything fine:

```Adding Filesystem Addon '/home/benrob0329/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/addons/doors'
Adding Filesystem Addon '/home/benrob0329/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/addons/tardis'
Adding Filesystem Addon '/home/benrob0329/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/addons/world-portals'
Error: Material "debug/debuglightmap" uses unknown shader "LightmappedGeneric_dx8"
Error: Material "debug/debugluxels" uses unknown shader "DebugLuxels"
Error: Material "___fillrate_0" uses unknown shader "FillRate"
Error: Material "___debugnormalmap_1" uses unknown shader "DebugNormalMap"
Error: Material "___debugdrawenvmapmask_2" uses unknown shader "DebugDrawEnvmapMask"
Error: Material "___debugdepth_3" uses unknown shader "DebugDepth"
Error: Material "___debugdepth_4" uses unknown shader "DebugDepth"```

But the TARDIS doesn't show up in the spawn menu:

![20160907135750_1](https://cloud.githubusercontent.com/assets/19180682/18322916/1c821abe-7503-11e6-80e7-73fb487b5727.jpg)

**Comment by benrob0329** [comment]
After a reinstall, the vortex does not seem to leave a shadow.
